apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
       containers:
        - name: trip-service
          image: 772584673213.dkr.ecr.us-east-2.amazonaws.com/stevenxs/trip-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8180
            name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
   externalTrafficPolicy: Local
   selector:
     app: trip-service
   ports:
   - name: http
     protocol: TCP
     port: 8180
     targetPort: 8180
   type: LoadBalancer